#!/bin/bash

set -euo pipefail

this_dir=$(readlink -qe "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )")
wd=$(readlink -qe "${this_dir}"/../)

cd "${wd}"

while read f ; do
    # echo "${f}"
    d=$(dirname "${f}")
    b="${d}"/index.html
    a="${d}"/$(basename "${f}")
	echo "${a} -> ${b}"
    minify --type html --html-keep-document-tags --html-keep-end-tags "${a}" > "${b}"
	echo ""
done < <(git status --short --porcelain | ag '^( M|\?\?)' | sed -re 's/^( M|\?\?) //g' | ag '\.raw\.html$' | sort --human)
# done < <(find "${wd}" -name index.raw.html)
